"""头像

Revision ID: 944194d0e1dc
Revises: 6db9acece744
Create Date: 2021-08-01 00:56:52.742737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944194d0e1dc'
down_revision = '6db9acece744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
